[package]
name = "shane/portal"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["bin", "client", "server", "Packages", "targets", "selene.toml", "roblox.toml"]

[dependencies]
t = "shanebutt/t@1.3.1"
Promise = "evaera/promise@3.1.0"