[package]
name = "shane/portal"
version = "0.5.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["bin", "blog", "demo", "docs", "Packages", "targets", "*.toml", "*.md", "*.js"]

[dependencies]
t = "osyrisrblx/t@3.0.0"